micronaut:
  application:
    name: micronaut-request-scope-in-filter
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  server:
    port: 8080